
"use client";

import * as React from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ShieldCheck, ArrowRight, Loader2, Sparkles, Database } from "lucide-react";
import Link from "next/link";
import { useLanguage } from "@/contexts/LanguageContext";
import { cn } from "@/lib/utils";
import { useUser, useFirestore, useDoc, useMemoFirebase } from "@/firebase";
import { doc } from "firebase/firestore";
import { useRouter } from "next/navigation";

/**
 * Gateway page for Administrators.
 * Points to both the TinaCMS visual editor and the operational Management Panel.
 */
export default function AdminGatewayPage() {
  const { language, t } = useLanguage();
  const { user, isUserLoading } = useUser();
  const firestore = useFirestore();
  const router = useRouter();

  const adminRoleRef = useMemoFirebase(() => {
    if (!firestore || !user) return null;
    return doc(firestore, "roles_admin", user.uid);
  }, [firestore, user]);
  const { data: adminDoc, isLoading: isAdminLoading } = useDoc(adminRoleRef);

  React.useEffect(() => {
    if (!isUserLoading && !user) {
      router.push("/login");
    }
  }, [user, isUserLoading, router]);

  if (isUserLoading || isAdminLoading) {
    return (
      <div className="min-h-screen bg-secondary/30 flex items-center justify-center p-4">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  if (!user || !adminDoc) {
    return (
      <div className="min-h-screen bg-secondary/30 flex items-center justify-center p-4 text-center">
        <div className="space-y-4">
          <ShieldCheck className="h-12 w-12 text-destructive mx-auto" />
          <h1 className="text-2xl font-bold">Access Denied</h1>
          <p className="text-muted-foreground">You do not have administrative privileges to access this area.</p>
          <Link href="/dashboard"><Button>Back to Dashboard</Button></Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-secondary/30 flex items-center justify-center p-4">
      <div className="max-w-4xl w-full grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card className="shadow-xl border-primary/10 overflow-hidden hover:shadow-2xl transition-all group">
          <CardHeader className="bg-primary/5 pb-8">
            <div className="h-12 w-12 bg-primary/10 rounded-xl flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
              <Sparkles className="h-6 w-6 text-primary" />
            </div>
            <CardTitle className={cn("text-2xl", language === 'hi' ? 'font-hindi' : 'font-headline')}>
              {language === 'hi' ? 'वेबसाइट कंटेंट' : 'TinaCMS Editor'}
            </CardTitle>
            <CardDescription>
              {language === 'hi' 
                ? 'विजुअल एडिटर का उपयोग करके हेडलाइन और पेज कंटेंट बदलें।' 
                : 'Use the visual editor to update headlines and page content.'}
            </CardDescription>
          </CardHeader>
          <CardContent className="pt-6">
            {/* Standard TinaCMS entry point generated by build */}
            <Link href="/admin/index.html">
              <Button className="w-full h-12 gap-2 font-bold shadow-md">
                {language === 'hi' ? 'एडिटर खोलें' : 'Open CMS Editor'}
                <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
            <p className="mt-4 text-[10px] text-muted-foreground text-center uppercase tracking-widest font-bold opacity-60">
              Powered by Tina Cloud
            </p>
          </CardContent>
        </Card>

        <Card className="shadow-xl border-accent/10 overflow-hidden hover:shadow-2xl transition-all group">
          <CardHeader className="bg-accent/5 pb-8">
            <div className="h-12 w-12 bg-accent/10 rounded-xl flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
              <Database className="h-6 w-6 text-accent" />
            </div>
            <CardTitle className={cn("text-2xl", language === 'hi' ? 'font-hindi' : 'font-headline')}>
              {language === 'hi' ? 'प्रबंधन पैनल' : 'Management Panel'}
            </CardTitle>
            <CardDescription>
              {language === 'hi' 
                ? 'दान, इवेंट्स और भक्तों के रिकॉर्ड प्रबंधित करें।' 
                : 'Handle daily operations: Donations, Events, and Members.'}
            </CardDescription>
          </CardHeader>
          <CardContent className="pt-6">
            <Link href="/management">
              <Button variant="secondary" className="w-full h-12 gap-2 font-bold shadow-md">
                {language === 'hi' ? 'पैनल खोलें' : 'Open Management'}
                <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
            <p className="mt-4 text-[10px] text-muted-foreground text-center uppercase tracking-widest font-bold opacity-60">
              Operational Dashboard
            </p>
          </CardContent>
        </Card>

        <div className="md:col-span-2 text-center pt-4">
          <Link href="/">
            <Button variant="ghost" className="gap-2 text-muted-foreground hover:text-primary">
              <ArrowRight className="h-4 w-4 rotate-180" />
              {t.backToHome}
            </Button>
          </Link>
        </div>
      </div>
    </div>
  );
}
