backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "settings"
    label: "General Settings"
    delete: false
    editor:
      preview: false
    files:
      - name: "identity"
        label: "Site Identity"
        file: "content/settings.json"
        fields:
          - { label: "Site Title (English)", name: "site_title_en", widget: "string" }
          - { label: "Site Title (Hindi)", name: "site_title_hi", widget: "string" }
          - { label: "Favicon", name: "favicon", widget: "image" }
